### ISSUE TITLE
"Font" in font-weight colored red

### ISSUE THREAD

**Issue by moll** [cakebaker/scss-syntax.vim#32]
Is it just me or is there a problem with parsing `font-weight`?

``` scss
td.today { color: $today-color; font-weight: bold; }
```

Looks like this:
![](https://s3.amazonaws.com/f.cl.ly/items/2C0C1C1f1I100y052S2p/Screen%20Shot%202013-12-26%20at%202.17.56%20AM.png)
